---
<<<<<<< HEAD
# tasks file for jenkins-salve-setup
- name: Create Jenkins user
  user: 
    name: jenkins
    password: "{{ jenkins_password }}"
=======
# tasks file for jenkins-slave-setup
- name: Create Jenkins user
  user:
    name: jenkins
    password: "{{ jenkins_password }}"
    shell: /bin/bash
>>>>>>> 2236983ea32a51aacbac222dabc2145101787915

- name: Create remote root directory
  file:
    path: "{{ remote_root_directory }}"
    state: directory
    owner: jenkins
    group: jenkins

- name: Install necessary packages for slave
  yum:
<<<<<<< HEAD
    name: "{{ item }}"
    state: present
  with_items:
    - java
    - python
=======
    name:
      - git
      - java
      - python36
      - python3-pip
      - epel-release
      - ansible
    state: present

- name: Add Jenkins to sudoers group
  become: true
  lineinfile:
    path: /etc/sudoers
    state: present
    line: "jenkins ALL=(ALL) NOPASSWD: ALL"
>>>>>>> 2236983ea32a51aacbac222dabc2145101787915

- name: Create .ssh directory
  file:
    path: /home/jenkins/.ssh
    state: directory
    owner: jenkins
    group: jenkins

- name: Copy master Jenkins public key
  copy:
    src: authorized_keys
<<<<<<< HEAD
    dest: /home/jenkins/.ssh/authorized_keys
=======
    dest: /home/jenkins/.ssh/authorized_keys
>>>>>>> 2236983ea32a51aacbac222dabc2145101787915
